//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjusteProducto
    {
        public int Id { get; set; }
        public int IdAjuste { get; set; }
        public int IdProducto { get; set; }
        public int Estado { get; set; }
        public decimal Saldo { get; set; }
        public decimal Fisico { get; set; }
        public decimal Diferencia { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public string Lote { get; set; }
        public System.DateTime FechaVen { get; set; }
    
        public virtual Ajuste Ajuste { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
