//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ajuste()
        {
            this.AjusteProducto = new HashSet<AjusteProducto>();
        }
    
        public int Id { get; set; }
        public int Estado { get; set; }
        public int IdAlmacen { get; set; }
        public int IdConcepto { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string Observacion { get; set; }
        public int TransportadorPor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual TCI001 TCI001 { get; set; }
        public virtual Almacen Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AjusteProducto> AjusteProducto { get; set; }
    }
}
