//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string IdSpyre { get; set; }
        public int Estado { get; set; }
        public string Descrip { get; set; }
        public string RazonSo { get; set; }
        public string Nit { get; set; }
        public int TipoCli { get; set; }
        public string Direcc { get; set; }
        public string Contac1 { get; set; }
        public string Contac2 { get; set; }
        public string Telfo1 { get; set; }
        public string Telfo2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public int Ciudad { get; set; }
        public int Factur { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longit { get; set; }
        public string Imagen { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    }
}
