//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_01
    {
        public int Id { get; set; }
        public int IdCompra { get; set; }
        public int IdProducto { get; set; }
        public int Estado { get; set; }
        public decimal Canti { get; set; }
        public decimal Costo { get; set; }
        public string Lote { get; set; }
        public System.DateTime FechaVen { get; set; }
        public decimal Utilidad { get; set; }
        public decimal Porcent { get; set; }
        public decimal Total { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
