//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraIng_01
    {
        public int Id { get; set; }
        public int IdCompra { get; set; }
        public int IdProduc { get; set; }
        public int Estado { get; set; }
        public decimal Caja { get; set; }
        public decimal Grupo { get; set; }
        public decimal Maple { get; set; }
        public decimal Cantidad { get; set; }
        public decimal TotalCant { get; set; }
        public decimal PrecioCost { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual CompraIng CompraIng { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
