//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiAviEntities : DbContext
    {
        public DiAviEntities()
            : base("name=DiAviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libreria> Libreria { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Compra_01> Compra_01 { get; set; }
        public virtual DbSet<Proveed> Proveed { get; set; }
        public virtual DbSet<Proveed_01> Proveed_01 { get; set; }
        public virtual DbSet<Deposito> Deposito { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Transformacion> Transformacion { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<PrecioCat> PrecioCat { get; set; }
        public virtual DbSet<Estaticos> Estaticos { get; set; }
        public virtual DbSet<Seleccion_01> Seleccion_01 { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Transformacion_01> Transformacion_01 { get; set; }
        public virtual DbSet<CompraIng_01> CompraIng_01 { get; set; }
        public virtual DbSet<V_NotaCompraIngreso> V_NotaCompraIngreso { get; set; }
        public virtual DbSet<CompraIng> CompraIng { get; set; }
        public virtual DbSet<Vr_CompraIngreso> Vr_CompraIngreso { get; set; }
        public virtual DbSet<Seleccion> Seleccion { get; set; }
    }
}
