//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiAviEntities : DbContext
    {
        public DiAviEntities()
            : base("name=DiAviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libreria> Libreria { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Compra_01> Compra_01 { get; set; }
        public virtual DbSet<Proveed> Proveed { get; set; }
        public virtual DbSet<Proveed_01> Proveed_01 { get; set; }
        public virtual DbSet<Deposito> Deposito { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Transformacion> Transformacion { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<PrecioCat> PrecioCat { get; set; }
        public virtual DbSet<Estaticos> Estaticos { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<CompraIng_01> CompraIng_01 { get; set; }
        public virtual DbSet<V_NotaCompraIngreso> V_NotaCompraIngreso { get; set; }
        public virtual DbSet<CompraIng> CompraIng { get; set; }
        public virtual DbSet<Vr_CompraIngreso> Vr_CompraIngreso { get; set; }
        public virtual DbSet<Seleccion> Seleccion { get; set; }
        public virtual DbSet<Transformacion_01> Transformacion_01 { get; set; }
        public virtual DbSet<Seleccion_01> Seleccion_01 { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Vr_TransformacionIngreso> Vr_TransformacionIngreso { get; set; }
        public virtual DbSet<Vr_TransformacionSalida> Vr_TransformacionSalida { get; set; }
        public virtual DbSet<TI002> TI002 { get; set; }
        public virtual DbSet<TI0021> TI0021 { get; set; }
    }
}
