//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantilla()
        {
            this.Plantilla_01 = new HashSet<Plantilla_01>();
        }
    
        public int Id { get; set; }
        public int IdAlmacen { get; set; }
        public int IdAlmacenDestino { get; set; }
        public int Concepto { get; set; }
        public string Nombre { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Almacen Almacen1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla_01> Plantilla_01 { get; set; }
    }
}
