//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int Id { get; set; }
        public int IdAlmac { get; set; }
        public int IdProduc { get; set; }
        public int IdPrecioCat { get; set; }
        public decimal Prrecio { get; set; }
        public Nullable<int> Oferta { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual PrecioCat PrecioCat { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
