//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveed_01
    {
        public int Id { get; set; }
        public int IdProveed { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string EdadSeman { get; set; }
        public decimal Cantidad { get; set; }
        public int Linea { get; set; }
        public int TipoAloja { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
    
        public virtual Proveed Proveed { get; set; }
    }
}
