//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveed_01
    {
        public int Id { get; set; }
        public int IdProveed { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string EdadSeman { get; set; }
        public decimal Cantidad { get; set; }
        public int Linea { get; set; }
        public int TipoAloja { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
    
        public virtual Proveed Proveed { get; set; }
    }
}
