//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Venta
    {
        public int ventaId { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string Cliente { get; set; }
        public string Nit { get; set; }
        public string FacturaExterna { get; set; }
        public int IdCompraIngreso { get; set; }
        public string alamcen { get; set; }
        public string EncEntrega { get; set; }
        public string encVenta { get; set; }
        public int detalleId { get; set; }
        public string Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal TotalUnidad { get; set; }
    }
}
