//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_AjusteFisico
    {
        public int AjusteId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string alamcen { get; set; }
        public string concepto { get; set; }
        public string Cliente { get; set; }
        public string almDestino { get; set; }
        public string RecibidoPor { get; set; }
        public string TransportadoPor { get; set; }
        public int detalleId { get; set; }
        public string Producto { get; set; }
        public decimal Diferencia { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
    }
}
