//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_01
    {
        public int IdRol_01 { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> Mod { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
