//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_01
    {
        public int IdRol_01 { get; set; }
        public int IdRol { get; set; }
        public int IdPrograma { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> Mod { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
