//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seleccion_01
    {
        public int Id { get; set; }
        public int IdSeleccion { get; set; }
        public int IdProducto { get; set; }
        public int Estado { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Porcen { get; set; }
    
        public virtual Seleccion Seleccion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
