//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY000
    {
        public int Modo { get; set; }
        public Nullable<int> Facturacion { get; set; }
        public string Grupo_1 { get; set; }
        public string Grupo_2 { get; set; }
        public string Grupo_3 { get; set; }
        public string Grupo_4 { get; set; }
        public Nullable<int> AyudaProd { get; set; }
        public Nullable<int> Cod1 { get; set; }
        public Nullable<int> Cod2 { get; set; }
        public string Con1 { get; set; }
        public Nullable<int> CodeBar { get; set; }
        public Nullable<decimal> PorcUtil { get; set; }
        public Nullable<int> VerPorc { get; set; }
        public Nullable<int> VerLote { get; set; }
        public Nullable<int> VerFactManual { get; set; }
        public Nullable<int> Mayusculas { get; set; }
    }
}
