//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB001
    {
        public int banumi { get; set; }
        public Nullable<int> banum { get; set; }
        public string baproc { get; set; }
        public Nullable<int> balinea { get; set; }
        public string bamensaje { get; set; }
        public Nullable<int> batipo { get; set; }
        public Nullable<System.DateTime> bafact { get; set; }
        public string bahact { get; set; }
        public Nullable<int> bauact { get; set; }
    }
}
