//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB001
    {
        public int banumi { get; set; }
        public Nullable<int> banum { get; set; }
        public string baproc { get; set; }
        public Nullable<int> balinea { get; set; }
        public string bamensaje { get; set; }
        public Nullable<int> batipo { get; set; }
        public Nullable<System.DateTime> bafact { get; set; }
        public string bahact { get; set; }
        public Nullable<int> bauact { get; set; }
    }
}
