//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCI001
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCI001()
        {
            this.TI002 = new HashSet<TI002>();
        }
    
        public int cpnumi { get; set; }
        public string cpdesc { get; set; }
        public int cpmov { get; set; }
        public int cpmovcli { get; set; }
        public int cptipo { get; set; }
        public int cpest { get; set; }
        public System.DateTime cpfact { get; set; }
        public string cphact { get; set; }
        public string cpuact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TI002> TI002 { get; set; }
    }
}
