//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCI001
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCI001()
        {
            this.TI002 = new HashSet<TI002>();
        }
    
        public int cpnumi { get; set; }
        public string cpdesc { get; set; }
        public Nullable<int> cpmov { get; set; }
        public Nullable<int> cpmovcli { get; set; }
        public Nullable<int> cptipo { get; set; }
        public Nullable<int> cpest { get; set; }
        public Nullable<System.DateTime> cpfact { get; set; }
        public string cphact { get; set; }
        public string cpuact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TI002> TI002 { get; set; }
    }
}
