//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI0021
    {
        public int icid { get; set; }
        public Nullable<int> icibid { get; set; }
        public Nullable<int> iccprod { get; set; }
        public Nullable<decimal> iccant { get; set; }
        public string iclot { get; set; }
        public Nullable<System.DateTime> icfvenc { get; set; }
    }
}
