//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI0021A
    {
        public int IdTI0021 { get; set; }
        public string Unidad { get; set; }
        public decimal Contenido { get; set; }
        public decimal Precio { get; set; }
    
        public virtual TI0021 TI0021 { get; set; }
    }
}
