//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI0021
    {
        public int icid { get; set; }
        public int icibid { get; set; }
        public int iccprod { get; set; }
        public decimal iccant { get; set; }
        public string iclot { get; set; }
        public System.DateTime icfvenc { get; set; }
        public int id { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TI0021A TI0021A { get; set; }
    }
}
