//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI001
    {
        public Nullable<int> icalm { get; set; }
        public string iccprod { get; set; }
        public Nullable<decimal> iccven { get; set; }
        public string icuven { get; set; }
        public string iclot { get; set; }
        public Nullable<System.DateTime> icfven { get; set; }
        public int id { get; set; }
    }
}
