//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI0021
    {
        public int icid { get; set; }
        public int icibid { get; set; }
        public int iccprod { get; set; }
        public decimal iccant { get; set; }
        public string iclot { get; set; }
        public System.DateTime icfvenc { get; set; }
        public int id { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TI0021A TI0021A { get; set; }
    }
}
