//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI002
    {
        public int ibid { get; set; }
        public Nullable<System.DateTime> ibfdoc { get; set; }
        public Nullable<int> ibconcep { get; set; }
        public string ibobs { get; set; }
        public Nullable<int> ibest { get; set; }
        public Nullable<int> ibalm { get; set; }
        public Nullable<int> ibdepdest { get; set; }
        public Nullable<int> ididdestino { get; set; }
        public Nullable<int> ibiddc { get; set; }
        public Nullable<System.DateTime> ibfact { get; set; }
        public string ibhact { get; set; }
        public string ibuact { get; set; }
        public int id { get; set; }
    }
}
