//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI002
    {
        public int ibid { get; set; }
        public System.DateTime ibfdoc { get; set; }
        public int ibconcep { get; set; }
        public string ibobs { get; set; }
        public int ibest { get; set; }
        public int ibalm { get; set; }
        public int ibdepdest { get; set; }
        public int ididdestino { get; set; }
        public int ibiddc { get; set; }
        public System.DateTime ibfact { get; set; }
        public string ibhact { get; set; }
        public string ibuact { get; set; }
        public int id { get; set; }
    
        public virtual TCI001 TCI001 { get; set; }
        public virtual Almacen Almacen { get; set; }
    }
}
