//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI002
    {
        public int ibid { get; set; }
        public System.DateTime ibfdoc { get; set; }
        public int ibconcep { get; set; }
        public string ibobs { get; set; }
        public int ibest { get; set; }
        public int ibalm { get; set; }
        public int ibdepdest { get; set; }
        public int ididdestino { get; set; }
        public int ibiddc { get; set; }
        public System.DateTime ibfact { get; set; }
        public string ibhact { get; set; }
        public string ibuact { get; set; }
        public int id { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual TCI001 TCI001 { get; set; }
    }
}
