//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI001
    {
        public Nullable<int> icalm { get; set; }
        public string iccprod { get; set; }
        public Nullable<decimal> iccven { get; set; }
        public string icuven { get; set; }
        public string iclot { get; set; }
        public Nullable<System.DateTime> icfven { get; set; }
        public int id { get; set; }
    }
}
