//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformacion_01
    {
        public int Id { get; set; }
        public int IdTransformacion { get; set; }
        public int IdProducto { get; set; }
        public int IdProducto_Mat { get; set; }
        public int Estado { get; set; }
        public decimal TotalProd { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual Transformacion Transformacion { get; set; }
    }
}
