//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspaso_01
    {
        public int Id { get; set; }
        public int IdTraspaso { get; set; }
        public int IdProducto { get; set; }
        public int Estado { get; set; }
        public decimal Cantidad { get; set; }
        public string Unidad { get; set; }
        public decimal Contenido { get; set; }
        public decimal TotalContenido { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public string Lote { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Traspaso Traspaso { get; set; }
    }
}
