//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspaso_02
    {
        public int Id { get; set; }
        public int TraspasoId { get; set; }
        public int AlmacenId { get; set; }
        public int Estado { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Traspaso Traspaso { get; set; }
    }
}
