//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspaso
    {
        public int Id { get; set; }
        public Nullable<int> AlmacenOrigen { get; set; }
        public Nullable<int> AlmacenDestino { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioEnvio { get; set; }
        public string UsuarioRecepcion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Almacen Almacen1 { get; set; }
    }
}
