//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_01
    {
        public int IdUsuario_01 { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
        public virtual Almacen Almacen { get; set; }
    }
}
