//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidacionPrograma
    {
        public int Id { get; set; }
        public int Estado { get; set; }
        public string TablaOrigen { get; set; }
        public string CampoOrigen { get; set; }
        public string TableDestino { get; set; }
        public string CampoDestino { get; set; }
        public string Programa { get; set; }
        public int IdGrupo { get; set; }
        public int IdOrden { get; set; }
    }
}
