//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Venta_01 = new HashSet<Venta_01>();
        }
    
        public int Id { get; set; }
        public int IdAlmacen { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string Usuario { get; set; }
        public int Estado { get; set; }
        public int Tipo { get; set; }
        public string Observaciones { get; set; }
        public string EncPrVenta { get; set; }
        public string EncVenta { get; set; }
        public string EncTransporte { get; set; }
        public string EncEntrega { get; set; }
        public string EncRecepcion { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_01> Venta_01 { get; set; }
    }
}
