//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vr_CompraIngreso
    {
        public int NotaRecepcion { get; set; }
        public string NotaGranja { get; set; }
        public System.DateTime FechaRecep { get; set; }
        public System.DateTime FechaEnt { get; set; }
        public string Codaparov { get; set; }
        public string Proveedor { get; set; }
        public string Descrip { get; set; }
        public decimal TotalCant { get; set; }
        public decimal PrecioCost { get; set; }
        public decimal Total { get; set; }
    }
}
