//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vr_CompraIngreso
    {
        public int NotaRecepcion { get; set; }
        public string NotaGranja { get; set; }
        public System.DateTime FechaRecep { get; set; }
        public System.DateTime FechaEnt { get; set; }
        public string Codaparov { get; set; }
        public string Proveedor { get; set; }
        public string Descrip { get; set; }
        public decimal TotalCant { get; set; }
        public decimal PrecioCost { get; set; }
        public decimal Total { get; set; }
    }
}
