//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vr_HistoricoSeleccion
    {
        public string IdSpyre { get; set; }
        public string Descrip { get; set; }
        public int ingreso { get; set; }
        public System.DateTime fecha { get; set; }
        public string NumNota { get; set; }
        public int Id { get; set; }
        public int Superc { get; set; }
        public int Especialc { get; set; }
        public int Primerac { get; set; }
        public int Segundac { get; set; }
        public int Tercerac { get; set; }
        public int Cuartac { get; set; }
        public int Quintac { get; set; }
        public int Picadoc { get; set; }
        public int manchadoc { get; set; }
        public Nullable<int> Merma { get; set; }
        public int Media_doc2 { get; set; }
        public int Docena2 { get; set; }
        public int Band2_12 { get; set; }
        public int Map2_6 { get; set; }
        public int Map2_10 { get; set; }
        public int Map2_12 { get; set; }
        public int Map2_15 { get; set; }
        public int Map2_18 { get; set; }
        public int Map2_20 { get; set; }
        public int Vit_Super { get; set; }
        public int Vit_Especial { get; set; }
        public int Vit_Primera { get; set; }
        public int Vit_Segunda { get; set; }
        public int Vit_Tercera { get; set; }
        public int Vit_Cuarta { get; set; }
        public int Vit_Quinta { get; set; }
        public int Vit_Map2_6 { get; set; }
        public int Vit_Map2_10 { get; set; }
        public int Vit_Map2_12 { get; set; }
        public int Vit_Map2_15 { get; set; }
        public int Vit_Map2_18 { get; set; }
        public int Vit_Map2_20 { get; set; }
        public int Omega_3 { get; set; }
        public int Omg_Med_Doc2 { get; set; }
        public int Omg_Docena2 { get; set; }
        public int Omg_Band2_12 { get; set; }
        public int Omg_Map2_10 { get; set; }
        public int Omg_Map2_20 { get; set; }
        public int Blanco_Super { get; set; }
        public int Blanco_Esp { get; set; }
        public int Blanco_Primera { get; set; }
        public int Blanco_Segunda { get; set; }
        public int Blanco_Tercera { get; set; }
        public int Blanco_Cuarta { get; set; }
        public int Blanco_Quinta { get; set; }
        public int Blanco_Band2_12 { get; set; }
        public int Blanco_Map2_20 { get; set; }
        public int Codorniz { get; set; }
        public int Color_Red50 { get; set; }
        public int Sedem_Maple1_30 { get; set; }
        public int Sedem_Map3_18X2 { get; set; }
        public int Sedem_Vit_Band2_12X2 { get; set; }
        public int Sedem_Omg_Nut_Map2_10X2 { get; set; }
        public int Sedem_Maple3_30 { get; set; }
        public int Sedem_Map2_12X2 { get; set; }
        public int Vacio1 { get; set; }
        public int Vacio2 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Tipo_Rec { get; set; }
        public System.DateTime Fecha_Recepcion { get; set; }
        public string Observacion { get; set; }
        public decimal Superp { get; set; }
        public decimal Especialp { get; set; }
        public decimal Primerap { get; set; }
        public decimal Segundap { get; set; }
        public decimal Tercerap { get; set; }
        public decimal Cuartap { get; set; }
        public decimal Quintap { get; set; }
        public decimal Picadop { get; set; }
        public decimal manchadop { get; set; }
        public string Mermap { get; set; }
        public string Media_doc2_P { get; set; }
        public string Docena2_P { get; set; }
        public string Band2_12_P { get; set; }
        public string Map2_6_P { get; set; }
        public string Map2_10_P { get; set; }
        public string Map2_12_P { get; set; }
        public string Map2_15_P { get; set; }
        public string Map2_18_P { get; set; }
        public string Map2_20_P { get; set; }
        public decimal Vit_SuperP { get; set; }
        public decimal Vit_EspecialP { get; set; }
        public decimal Vit_PrimeraP { get; set; }
        public decimal Vit_SegundaP { get; set; }
        public decimal Vit_TerceraP { get; set; }
        public decimal Vit_CuartaP { get; set; }
        public decimal Vit_QuintaP { get; set; }
        public int Vit_Map2_6_P { get; set; }
        public int Vit_Map2_10_P { get; set; }
        public int Vit_Map2_12_P { get; set; }
        public int Vit_Map2_15_P { get; set; }
        public int Vit_Map2_18_P { get; set; }
        public int Vit_Map2_20_P { get; set; }
        public int Vit_Media_Doc2_P { get; set; }
        public int vit_Docena2_P { get; set; }
        public int vit_Band2_12_P { get; set; }
        public decimal Omega_3_P { get; set; }
        public int Omg_Med_Doc2_P { get; set; }
        public int Omg_Docena2_P { get; set; }
        public int Omg_Band2_12_P { get; set; }
        public int Omg_Map2_10_P { get; set; }
        public int Omg_Map2_20_P { get; set; }
        public decimal Blanco_Super_P { get; set; }
        public decimal Blanco_Esp_P { get; set; }
        public decimal Blanco_Primera_P { get; set; }
        public decimal Blanco_Segunda_P { get; set; }
        public decimal Blanco_Tercera_P { get; set; }
        public decimal Blanco_Cuarta_P { get; set; }
        public decimal Blanco_Quinta_P { get; set; }
        public int Blanco_Band2_12_P { get; set; }
        public int Blanco_Map2_20_P { get; set; }
        public decimal Codorniz_P { get; set; }
        public int Color_Red50_P { get; set; }
        public int Sedem_Maple1_30_P { get; set; }
        public int Sedem_Map3_18X2_P { get; set; }
        public int Sedem_Vit_Band2_12X2_P { get; set; }
        public int Sedem_Omg_Nut_Map2_10X2_P { get; set; }
        public int Sedem_Maple3_30_P { get; set; }
        public int Sedem_Map2_12X2_P { get; set; }
        public int Vacio3 { get; set; }
        public int Vacio4 { get; set; }
        public decimal Precio_Promedio { get; set; }
        public decimal Total_Bs { get; set; }
        public Nullable<decimal> Peso_Promedio { get; set; }
    }
}
