//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vr_SeleccionNota
    {
        public int Id { get; set; }
        public int IdCompraIng { get; set; }
        public string NumNota { get; set; }
        public System.DateTime FechaReg { get; set; }
        public System.DateTime FechaRec { get; set; }
        public string Proveedor { get; set; }
        public string IdSpyre { get; set; }
        public string MarcaTipo { get; set; }
        public string Entregado { get; set; }
        public string DescripcionRecibido { get; set; }
        public int IdDetalle { get; set; }
        public int IdProducto { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Porcen { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public decimal Merma { get; set; }
        public decimal MermaPorcentaje { get; set; }
    }
}
