//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vr_TransformacionIngreso
    {
        public int Id { get; set; }
        public string AlmacenIngreso { get; set; }
        public string AlmacenSalida { get; set; }
        public string Observ { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdProducto { get; set; }
        public string Descrip { get; set; }
        public decimal TotalProd { get; set; }
        public int IdProducto_Mat { get; set; }
        public string MateriaPrima { get; set; }
        public decimal TotalMateriaPrima { get; set; }
        public decimal Cantidad { get; set; }
    }
}
