//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZY0021
    {
        public int ycline { get; set; }
        public Nullable<int> ycnumi { get; set; }
        public Nullable<int> ycyanumi { get; set; }
        public Nullable<bool> ycshow { get; set; }
        public Nullable<bool> ycadd { get; set; }
        public Nullable<bool> ycmod { get; set; }
        public Nullable<bool> ycdel { get; set; }
    }
}
