//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiAvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZY0021
    {
        public int ycline { get; set; }
        public Nullable<int> ycnumi { get; set; }
        public Nullable<int> ycyanumi { get; set; }
        public Nullable<bool> ycshow { get; set; }
        public Nullable<bool> ycadd { get; set; }
        public Nullable<bool> ycmod { get; set; }
        public Nullable<bool> ycdel { get; set; }
    }
}
