//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC0051
    {
        public int ceId { get; set; }
        public Nullable<int> cecon { get; set; }
        public Nullable<int> cenum { get; set; }
        public string cedesc { get; set; }
        public Nullable<System.DateTime> cefact { get; set; }
        public string cehact { get; set; }
        public string ceuact { get; set; }
    }
}
