//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC0041
    {
        public int chnumi { get; set; }
        public Nullable<System.DateTime> chfec { get; set; }
        public string chcod { get; set; }
        public string chdesc { get; set; }
        public Nullable<int> chtmov { get; set; }
        public Nullable<int> chnrem { get; set; }
        public Nullable<double> chcan { get; set; }
        public Nullable<double> chmonbs { get; set; }
        public Nullable<double> chmonsus { get; set; }
        public Nullable<int> chnota { get; set; }
        public int chlin { get; set; }
        public string chobs { get; set; }
        public Nullable<System.DateTime> chfact { get; set; }
        public string chhact { get; set; }
        public string chuact { get; set; }
    }
}
