//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC004
    {
        public int ccnumi { get; set; }
        public string cccod { get; set; }
        public string ccdesc { get; set; }
        public Nullable<int> cczona { get; set; }
        public int ccdct { get; set; }
        public string ccdctnum { get; set; }
        public string ccdirec { get; set; }
        public string cctelf1 { get; set; }
        public string cctelf2 { get; set; }
        public Nullable<int> cccat { get; set; }
        public Nullable<int> ccest { get; set; }
        public Nullable<decimal> cclat { get; set; }
        public Nullable<decimal> cclongi { get; set; }
        public Nullable<int> ccprconsu { get; set; }
        public Nullable<bool> cceven { get; set; }
        public string ccobs { get; set; }
        public Nullable<System.DateTime> ccfnac { get; set; }
        public string ccnomfac { get; set; }
        public string ccnit { get; set; }
        public Nullable<System.DateTime> ccultped { get; set; }
        public Nullable<System.DateTime> ccfecing { get; set; }
        public Nullable<System.DateTime> ccultvent { get; set; }
        public Nullable<int> ccrecven { get; set; }
        public Nullable<int> ccsupven { get; set; }
        public Nullable<int> ccpreven { get; set; }
        public string ccemail { get; set; }
        public string ccref { get; set; }
        public string ccpass { get; set; }
        public Nullable<System.DateTime> ccfact { get; set; }
        public string cchact { get; set; }
        public string ccuact { get; set; }
        public Nullable<decimal> ccLimite { get; set; }
        public Nullable<decimal> ccDias { get; set; }
    }
}
