//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC001
    {
        public int canumi { get; set; }
        public string cacod { get; set; }
        public string cadesc { get; set; }
        public string cadesc2 { get; set; }
        public Nullable<int> cacat { get; set; }
        public string caimg { get; set; }
        public Nullable<bool> castc { get; set; }
        public Nullable<bool> caest { get; set; }
        public Nullable<bool> caserie { get; set; }
        public Nullable<int> capcom { get; set; }
        public Nullable<System.DateTime> cafing { get; set; }
        public Nullable<int> cacemp { get; set; }
        public Nullable<System.DateTime> cafact { get; set; }
        public string cahact { get; set; }
        public string cauact { get; set; }
        public string cacbarra { get; set; }
        public Nullable<int> casmin { get; set; }
        public Nullable<int> cagr1 { get; set; }
        public Nullable<int> cagr2 { get; set; }
        public Nullable<int> cagr3 { get; set; }
        public Nullable<int> cagr4 { get; set; }
        public Nullable<int> caumed { get; set; }
        public Nullable<int> cauventa { get; set; }
        public Nullable<int> caumax { get; set; }
        public Nullable<decimal> caconv { get; set; }
        public Nullable<int> capack { get; set; }
    }
}
