//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC002
    {
        public int cbnumi { get; set; }
        public string cbdesc { get; set; }
        public string cbdirec { get; set; }
        public string cbtelef { get; set; }
        public Nullable<int> cbcat { get; set; }
        public Nullable<decimal> cbsal { get; set; }
        public string cbci { get; set; }
        public string cbobs { get; set; }
        public Nullable<System.DateTime> cbfnac { get; set; }
        public Nullable<System.DateTime> cbfing { get; set; }
        public Nullable<System.DateTime> cbfret { get; set; }
        public string cbfot { get; set; }
        public Nullable<bool> cbest { get; set; }
        public string cbeciv { get; set; }
        public Nullable<int> cbplan { get; set; }
        public Nullable<int> cbreloj { get; set; }
        public Nullable<System.DateTime> cbfact { get; set; }
        public string cbhact { get; set; }
        public string cbuact { get; set; }
    }
}
