//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL001
    {
        public int lanumi { get; set; }
        public Nullable<int> lacity { get; set; }
        public Nullable<int> laprovi { get; set; }
        public Nullable<int> lazona { get; set; }
        public string lacolor { get; set; }
        public Nullable<System.DateTime> lafact { get; set; }
        public string lahact { get; set; }
        public string lauact { get; set; }
    }
}
