//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO001
    {
        public int oanumi { get; set; }
        public Nullable<System.DateTime> oafdoc { get; set; }
        public string oahora { get; set; }
        public Nullable<int> oaccli { get; set; }
        public Nullable<int> oazona { get; set; }
        public Nullable<int> oarepa { get; set; }
        public string oaobs { get; set; }
        public string oaobs2 { get; set; }
        public Nullable<int> oaest { get; set; }
        public Nullable<int> oaap { get; set; }
        public Nullable<int> oapg { get; set; }
        public Nullable<System.DateTime> oafact { get; set; }
        public string oahact { get; set; }
        public string oauact { get; set; }
    }
}
