//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO0011
    {
        public int obnumi { get; set; }
        public string obcprod { get; set; }
        public Nullable<decimal> obpcant { get; set; }
        public Nullable<decimal> obpbase { get; set; }
        public Nullable<decimal> obptot { get; set; }
        public Nullable<decimal> obdesc { get; set; }
        public Nullable<decimal> obtotal { get; set; }
        public Nullable<int> obfamilia { get; set; }
        public Nullable<int> obcampo1 { get; set; }
        public Nullable<decimal> obcampo2 { get; set; }
        public int IdPedidoDetalle { get; set; }
    }
}
