//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO001A1
    {
        public Nullable<int> ognumi { get; set; }
        public Nullable<decimal> ogcred { get; set; }
        public int Id { get; set; }
    }
}
