//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO001C
    {
        public int oacnumi { get; set; }
        public int oacoanumi { get; set; }
        public int oaccbnumi { get; set; }
        public Nullable<long> oacnrofac { get; set; }
        public Nullable<int> oacnconc { get; set; }
        public System.DateTime oacfdoc { get; set; }
    }
}
