//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EntityDataModel.DiSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO001A
    {
        public int oaanumi { get; set; }
        public Nullable<int> oaato1numi { get; set; }
        public Nullable<int> oaanumiprev { get; set; }
        public Nullable<int> oaaentrega { get; set; }
        public Nullable<int> oaacaja { get; set; }
    }
}
