//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESENTER.ServiceDesktop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SERVICE")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDesktop.IServiceDesktop")]
    public interface IServiceDesktop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/GetData", ReplyAction="http://tempuri.org/IServiceDesktop/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/GetData", ReplyAction="http://tempuri.org/IServiceDesktop/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceDesktop/GetDataUsingDataContractResponse")]
        PRESENTER.ServiceDesktop.CompositeType GetDataUsingDataContract(PRESENTER.ServiceDesktop.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceDesktop/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.CompositeType> GetDataUsingDataContractAsync(PRESENTER.ServiceDesktop.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/LibreriaListarCombo", ReplyAction="http://tempuri.org/IServiceDesktop/LibreriaListarComboResponse")]
        ENTITY.Libreria.View.VLibreria[] LibreriaListarCombo(int idGrupo, int idOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/LibreriaListarCombo", ReplyAction="http://tempuri.org/IServiceDesktop/LibreriaListarComboResponse")]
        System.Threading.Tasks.Task<ENTITY.Libreria.View.VLibreria[]> LibreriaListarComboAsync(int idGrupo, int idOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/LibreriaGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/LibreriaGuardarResponse")]
        bool LibreriaGuardar(ENTITY.Libreria.View.VLibreriaLista vlibreria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/LibreriaGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/LibreriaGuardarResponse")]
        System.Threading.Tasks.Task<bool> LibreriaGuardarAsync(ENTITY.Libreria.View.VLibreriaLista vlibreria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteListar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteListarResponse")]
        ENTITY.Cliente.View.VCliente[] ClienteListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteListar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteListarResponse")]
        System.Threading.Tasks.Task<ENTITY.Cliente.View.VCliente[]> ClienteListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteGuardarResponse")]
        PRESENTER.ServiceDesktop.ClienteGuardarResponse ClienteGuardar(PRESENTER.ServiceDesktop.ClienteGuardarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteGuardarResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ClienteGuardarResponse> ClienteGuardarAsync(PRESENTER.ServiceDesktop.ClienteGuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteModificar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteModificarResponse")]
        bool ClienteModificar(ENTITY.Cliente.View.VCliente cliente, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteModificar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteModificarResponse")]
        System.Threading.Tasks.Task<bool> ClienteModificarAsync(ENTITY.Cliente.View.VCliente cliente, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteEliminar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteEliminarResponse")]
        bool ClienteEliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteEliminar", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteEliminarResponse")]
        System.Threading.Tasks.Task<bool> ClienteEliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteListar1", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteListar1Response")]
        ENTITY.Cliente.View.VCliente[] ClienteListar1(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClienteListar1", ReplyAction="http://tempuri.org/IServiceDesktop/ClienteListar1Response")]
        System.Threading.Tasks.Task<ENTITY.Cliente.View.VCliente[]> ClienteListar1Async(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClientesListar", ReplyAction="http://tempuri.org/IServiceDesktop/ClientesListarResponse")]
        ENTITY.Cliente.View.VClienteLista[] ClientesListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ClientesListar", ReplyAction="http://tempuri.org/IServiceDesktop/ClientesListarResponse")]
        System.Threading.Tasks.Task<ENTITY.Cliente.View.VClienteLista[]> ClientesListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorGuardarResponse")]
        PRESENTER.ServiceDesktop.ProveedorGuardarResponse ProveedorGuardar(PRESENTER.ServiceDesktop.ProveedorGuardarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorGuardarResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ProveedorGuardarResponse> ProveedorGuardarAsync(PRESENTER.ServiceDesktop.ProveedorGuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarXIdResponse")]
        ENTITY.Proveedor.View.VProveedor[] ProveedorListarXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedor[]> ProveedorListarXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListar", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarResponse")]
        ENTITY.Proveedor.View.VProveedorLista[] ProveedorListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListar", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarResponse")]
        System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedorLista[]> ProveedorListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListarEncabezado", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarEncabezadoResponse")]
        System.Data.DataTable ProveedorListarEncabezado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProveedorListarEncabezado", ReplyAction="http://tempuri.org/IServiceDesktop/ProveedorListarEncabezadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProveedorListarEncabezadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Proveedor_01ListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/Proveedor_01ListarXIdResponse")]
        ENTITY.Proveedor.View.VProveedor_01Lista[] Proveedor_01ListarXId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Proveedor_01ListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/Proveedor_01ListarXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedor_01Lista[]> Proveedor_01ListarXIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoGuardarResponse")]
        PRESENTER.ServiceDesktop.ProductoGuardarResponse ProductoGuardar(PRESENTER.ServiceDesktop.ProductoGuardarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoGuardar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoGuardarResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ProductoGuardarResponse> ProductoGuardarAsync(PRESENTER.ServiceDesktop.ProductoGuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoModificar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoModificarResponse")]
        bool ProductoModificar(ENTITY.Producto.View.VProducto proveedor, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoModificar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoModificarResponse")]
        System.Threading.Tasks.Task<bool> ProductoModificarAsync(ENTITY.Producto.View.VProducto proveedor, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoEliminar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoEliminarResponse")]
        bool ProductoEliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoEliminar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoEliminarResponse")]
        System.Threading.Tasks.Task<bool> ProductoEliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoListarXIdResponse")]
        ENTITY.Producto.View.VProducto[] ProductoListarXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoListarXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.Producto.View.VProducto[]> ProductoListarXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoListar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoListarResponse")]
        ENTITY.Producto.View.VProductoLista[] ProductoListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoListar", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoListarResponse")]
        System.Threading.Tasks.Task<ENTITY.Producto.View.VProductoLista[]> ProductoListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoExisteEnCompra", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoExisteEnCompraResponse")]
        bool ProductoExisteEnCompra(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/ProductoExisteEnCompra", ReplyAction="http://tempuri.org/IServiceDesktop/ProductoExisteEnCompraResponse")]
        System.Threading.Tasks.Task<bool> ProductoExisteEnCompraAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/SucursalListarCombo", ReplyAction="http://tempuri.org/IServiceDesktop/SucursalListarComboResponse")]
        ENTITY.inv.Sucursal.View.VSucursalCombo[] SucursalListarCombo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/SucursalListarCombo", ReplyAction="http://tempuri.org/IServiceDesktop/SucursalListarComboResponse")]
        System.Threading.Tasks.Task<ENTITY.inv.Sucursal.View.VSucursalCombo[]> SucursalListarComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/SucursalListar", ReplyAction="http://tempuri.org/IServiceDesktop/SucursalListarResponse")]
        ENTITY.inv.Sucursal.View.VSucursalLista[] SucursalListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/SucursalListar", ReplyAction="http://tempuri.org/IServiceDesktop/SucursalListarResponse")]
        System.Threading.Tasks.Task<ENTITY.inv.Sucursal.View.VSucursalLista[]> SucursalListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/PrecioCategoriaListar", ReplyAction="http://tempuri.org/IServiceDesktop/PrecioCategoriaListarResponse")]
        ENTITY.reg.PrecioCategoria.View.VPrecioCategoria[] PrecioCategoriaListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/PrecioCategoriaListar", ReplyAction="http://tempuri.org/IServiceDesktop/PrecioCategoriaListarResponse")]
        System.Threading.Tasks.Task<ENTITY.reg.PrecioCategoria.View.VPrecioCategoria[]> PrecioCategoriaListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/PrecioProductoListar", ReplyAction="http://tempuri.org/IServiceDesktop/PrecioProductoListarResponse")]
        ENTITY.reg.Precio.View.VPrecioLista[] PrecioProductoListar(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/PrecioProductoListar", ReplyAction="http://tempuri.org/IServiceDesktop/PrecioProductoListarResponse")]
        System.Threading.Tasks.Task<ENTITY.reg.Precio.View.VPrecioLista[]> PrecioProductoListarAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngresoListar", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarResponse")]
        ENTITY.com.CompraIngreso.View.VCompraIngreso[] CmmpraIngresoListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngresoListar", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarResponse")]
        System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngreso[]> CmmpraIngresoListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarXIdResponse")]
        ENTITY.com.CompraIngreso.View.VCompraIngresoLista[] CmmpraIngresoListarXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngresoListarXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngresoLista[]> CmmpraIngresoListarXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_NotaXId", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_NotaXIdResponse")]
        ENTITY.com.CompraIngreso.View.VCompraIngresoNota[] CompraIngreso_NotaXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_NotaXId", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_NotaXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngresoNota[]> CompraIngreso_NotaXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_Guardar", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_GuardarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ENTITY.com.CompraIngreso.View.VCompraIngresoNota))]
        PRESENTER.ServiceDesktop.CompraIngreso_GuardarResponse CompraIngreso_Guardar(PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_Guardar", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_GuardarResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.CompraIngreso_GuardarResponse> CompraIngreso_GuardarAsync(PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_ListarEncabezado", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_ListarEncabezadoResponse")]
        System.Data.DataTable CompraIngreso_ListarEncabezado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CompraIngreso_ListarEncabezado", ReplyAction="http://tempuri.org/IServiceDesktop/CompraIngreso_ListarEncabezadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> CompraIngreso_ListarEncabezadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXIdResponse")]
        ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] CmmpraIngreso_01ListarXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXIdResponse")]
        System.Threading.Tasks.Task<ENTITY.com.CompraIngreso_01.VCompraIngreso_01[]> CmmpraIngreso_01ListarXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId2", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId2Response")]
        ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] CmmpraIngreso_01ListarXId2(int IdGrupo2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId2", ReplyAction="http://tempuri.org/IServiceDesktop/CmmpraIngreso_01ListarXId2Response")]
        System.Threading.Tasks.Task<ENTITY.com.CompraIngreso_01.VCompraIngreso_01[]> CmmpraIngreso_01ListarXId2Async(int IdGrupo2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_ListaResponse")]
        ENTITY.com.Seleccion.View.VSeleccionLista[] Seleccion_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.com.Seleccion.View.VSeleccionLista[]> Seleccion_ListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_Guardar", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_GuardarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ENTITY.com.Seleccion.View.VSeleccionLista))]
        PRESENTER.ServiceDesktop.Seleccion_GuardarResponse Seleccion_Guardar(PRESENTER.ServiceDesktop.Seleccion_GuardarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_Guardar", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_GuardarResponse")]
        System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.Seleccion_GuardarResponse> Seleccion_GuardarAsync(PRESENTER.ServiceDesktop.Seleccion_GuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_01_ListaResponse")]
        ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[] Seleccion_01_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_01_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[]> Seleccion_01_ListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_01_ListarXId_Vacio", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_01_ListarXId_VacioResponse")]
        ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[] Seleccion_01_ListarXId_Vacio(int IdCompraInreso_01);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Seleccion_01_ListarXId_Vacio", ReplyAction="http://tempuri.org/IServiceDesktop/Seleccion_01_ListarXId_VacioResponse")]
        System.Threading.Tasks.Task<ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[]> Seleccion_01_ListarXId_VacioAsync(int IdCompraInreso_01);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Transformacion_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Transformacion_ListaResponse")]
        ENTITY.inv.Transformacion.View.VTransformacion[] Transformacion_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Transformacion_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Transformacion_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.inv.Transformacion.View.VTransformacion[]> Transformacion_ListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Transformacion_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Transformacion_01_ListaResponse")]
        ENTITY.inv.Transformacion_01.View.VTransformacion_01_Lista[] Transformacion_01_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Transformacion_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Transformacion_01_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.inv.Transformacion_01.View.VTransformacion_01_Lista[]> Transformacion_01_ListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Compra_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Compra_ListaResponse")]
        ENTITY.com.Compra.View.VCompraLista[] Compra_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Compra_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Compra_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.com.Compra.View.VCompraLista[]> Compra_ListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Compra_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Compra_01_ListaResponse")]
        ENTITY.com.Compra_01.View.VCompra_01_Lista[] Compra_01_Lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDesktop/Compra_01_Lista", ReplyAction="http://tempuri.org/IServiceDesktop/Compra_01_ListaResponse")]
        System.Threading.Tasks.Task<ENTITY.com.Compra_01.View.VCompra_01_Lista[]> Compra_01_ListaAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClienteGuardar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClienteGuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ENTITY.Cliente.View.VCliente cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public ClienteGuardarRequest() {
        }
        
        public ClienteGuardarRequest(ENTITY.Cliente.View.VCliente cliente, int id) {
            this.cliente = cliente;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClienteGuardarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClienteGuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ClienteGuardarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public ClienteGuardarResponse() {
        }
        
        public ClienteGuardarResponse(bool ClienteGuardarResult, int id) {
            this.ClienteGuardarResult = ClienteGuardarResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProveedorGuardar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProveedorGuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ENTITY.Proveedor.View.VProveedor proveedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ENTITY.Proveedor.View.VProveedor_01Lista[] detalle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string usuario;
        
        public ProveedorGuardarRequest() {
        }
        
        public ProveedorGuardarRequest(ENTITY.Proveedor.View.VProveedor proveedor, ENTITY.Proveedor.View.VProveedor_01Lista[] detalle, int id, string usuario) {
            this.proveedor = proveedor;
            this.detalle = detalle;
            this.id = id;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProveedorGuardarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProveedorGuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProveedorGuardarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public ProveedorGuardarResponse() {
        }
        
        public ProveedorGuardarResponse(bool ProveedorGuardarResult, int id) {
            this.ProveedorGuardarResult = ProveedorGuardarResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductoGuardar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProductoGuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ENTITY.Producto.View.VProducto proveedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public ProductoGuardarRequest() {
        }
        
        public ProductoGuardarRequest(ENTITY.Producto.View.VProducto proveedor, int id) {
            this.proveedor = proveedor;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductoGuardarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProductoGuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProductoGuardarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public ProductoGuardarResponse() {
        }
        
        public ProductoGuardarResponse(bool ProductoGuardarResult, int id) {
            this.ProductoGuardarResult = ProductoGuardarResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompraIngreso_Guardar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompraIngreso_GuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ENTITY.com.CompraIngreso.View.VCompraIngresoLista proveedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] detalle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string usuario;
        
        public CompraIngreso_GuardarRequest() {
        }
        
        public CompraIngreso_GuardarRequest(ENTITY.com.CompraIngreso.View.VCompraIngresoLista proveedor, ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] detalle, int id, string usuario) {
            this.proveedor = proveedor;
            this.detalle = detalle;
            this.id = id;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompraIngreso_GuardarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompraIngreso_GuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CompraIngreso_GuardarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public CompraIngreso_GuardarResponse() {
        }
        
        public CompraIngreso_GuardarResponse(bool CompraIngreso_GuardarResult, int id) {
            this.CompraIngreso_GuardarResult = CompraIngreso_GuardarResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Seleccion_Guardar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Seleccion_GuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ENTITY.com.Seleccion.View.VSeleccion vSeleccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ENTITY.com.Seleccion_01.View.VSeleccion_01[] detalle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string usuario;
        
        public Seleccion_GuardarRequest() {
        }
        
        public Seleccion_GuardarRequest(ENTITY.com.Seleccion.View.VSeleccion vSeleccion, ENTITY.com.Seleccion_01.View.VSeleccion_01[] detalle, int id, string usuario) {
            this.vSeleccion = vSeleccion;
            this.detalle = detalle;
            this.id = id;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Seleccion_GuardarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Seleccion_GuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Seleccion_GuardarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public Seleccion_GuardarResponse() {
        }
        
        public Seleccion_GuardarResponse(bool Seleccion_GuardarResult, int id) {
            this.Seleccion_GuardarResult = Seleccion_GuardarResult;
            this.id = id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDesktopChannel : PRESENTER.ServiceDesktop.IServiceDesktop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDesktopClient : System.ServiceModel.ClientBase<PRESENTER.ServiceDesktop.IServiceDesktop>, PRESENTER.ServiceDesktop.IServiceDesktop {
        
        public ServiceDesktopClient() {
        }
        
        public ServiceDesktopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDesktopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDesktopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDesktopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PRESENTER.ServiceDesktop.CompositeType GetDataUsingDataContract(PRESENTER.ServiceDesktop.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.CompositeType> GetDataUsingDataContractAsync(PRESENTER.ServiceDesktop.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ENTITY.Libreria.View.VLibreria[] LibreriaListarCombo(int idGrupo, int idOrden) {
            return base.Channel.LibreriaListarCombo(idGrupo, idOrden);
        }
        
        public System.Threading.Tasks.Task<ENTITY.Libreria.View.VLibreria[]> LibreriaListarComboAsync(int idGrupo, int idOrden) {
            return base.Channel.LibreriaListarComboAsync(idGrupo, idOrden);
        }
        
        public bool LibreriaGuardar(ENTITY.Libreria.View.VLibreriaLista vlibreria) {
            return base.Channel.LibreriaGuardar(vlibreria);
        }
        
        public System.Threading.Tasks.Task<bool> LibreriaGuardarAsync(ENTITY.Libreria.View.VLibreriaLista vlibreria) {
            return base.Channel.LibreriaGuardarAsync(vlibreria);
        }
        
        public ENTITY.Cliente.View.VCliente[] ClienteListar() {
            return base.Channel.ClienteListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.Cliente.View.VCliente[]> ClienteListarAsync() {
            return base.Channel.ClienteListarAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESENTER.ServiceDesktop.ClienteGuardarResponse PRESENTER.ServiceDesktop.IServiceDesktop.ClienteGuardar(PRESENTER.ServiceDesktop.ClienteGuardarRequest request) {
            return base.Channel.ClienteGuardar(request);
        }
        
        public bool ClienteGuardar(ENTITY.Cliente.View.VCliente cliente, ref int id) {
            PRESENTER.ServiceDesktop.ClienteGuardarRequest inValue = new PRESENTER.ServiceDesktop.ClienteGuardarRequest();
            inValue.cliente = cliente;
            inValue.id = id;
            PRESENTER.ServiceDesktop.ClienteGuardarResponse retVal = ((PRESENTER.ServiceDesktop.IServiceDesktop)(this)).ClienteGuardar(inValue);
            id = retVal.id;
            return retVal.ClienteGuardarResult;
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ClienteGuardarResponse> ClienteGuardarAsync(PRESENTER.ServiceDesktop.ClienteGuardarRequest request) {
            return base.Channel.ClienteGuardarAsync(request);
        }
        
        public bool ClienteModificar(ENTITY.Cliente.View.VCliente cliente, int id) {
            return base.Channel.ClienteModificar(cliente, id);
        }
        
        public System.Threading.Tasks.Task<bool> ClienteModificarAsync(ENTITY.Cliente.View.VCliente cliente, int id) {
            return base.Channel.ClienteModificarAsync(cliente, id);
        }
        
        public bool ClienteEliminar(int id) {
            return base.Channel.ClienteEliminar(id);
        }
        
        public System.Threading.Tasks.Task<bool> ClienteEliminarAsync(int id) {
            return base.Channel.ClienteEliminarAsync(id);
        }
        
        public ENTITY.Cliente.View.VCliente[] ClienteListar1(int id) {
            return base.Channel.ClienteListar1(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.Cliente.View.VCliente[]> ClienteListar1Async(int id) {
            return base.Channel.ClienteListar1Async(id);
        }
        
        public ENTITY.Cliente.View.VClienteLista[] ClientesListar() {
            return base.Channel.ClientesListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.Cliente.View.VClienteLista[]> ClientesListarAsync() {
            return base.Channel.ClientesListarAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESENTER.ServiceDesktop.ProveedorGuardarResponse PRESENTER.ServiceDesktop.IServiceDesktop.ProveedorGuardar(PRESENTER.ServiceDesktop.ProveedorGuardarRequest request) {
            return base.Channel.ProveedorGuardar(request);
        }
        
        public bool ProveedorGuardar(ENTITY.Proveedor.View.VProveedor proveedor, ENTITY.Proveedor.View.VProveedor_01Lista[] detalle, ref int id, string usuario) {
            PRESENTER.ServiceDesktop.ProveedorGuardarRequest inValue = new PRESENTER.ServiceDesktop.ProveedorGuardarRequest();
            inValue.proveedor = proveedor;
            inValue.detalle = detalle;
            inValue.id = id;
            inValue.usuario = usuario;
            PRESENTER.ServiceDesktop.ProveedorGuardarResponse retVal = ((PRESENTER.ServiceDesktop.IServiceDesktop)(this)).ProveedorGuardar(inValue);
            id = retVal.id;
            return retVal.ProveedorGuardarResult;
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ProveedorGuardarResponse> ProveedorGuardarAsync(PRESENTER.ServiceDesktop.ProveedorGuardarRequest request) {
            return base.Channel.ProveedorGuardarAsync(request);
        }
        
        public ENTITY.Proveedor.View.VProveedor[] ProveedorListarXId(int id) {
            return base.Channel.ProveedorListarXId(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedor[]> ProveedorListarXIdAsync(int id) {
            return base.Channel.ProveedorListarXIdAsync(id);
        }
        
        public ENTITY.Proveedor.View.VProveedorLista[] ProveedorListar() {
            return base.Channel.ProveedorListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedorLista[]> ProveedorListarAsync() {
            return base.Channel.ProveedorListarAsync();
        }
        
        public System.Data.DataTable ProveedorListarEncabezado() {
            return base.Channel.ProveedorListarEncabezado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProveedorListarEncabezadoAsync() {
            return base.Channel.ProveedorListarEncabezadoAsync();
        }
        
        public ENTITY.Proveedor.View.VProveedor_01Lista[] Proveedor_01ListarXId(int Id) {
            return base.Channel.Proveedor_01ListarXId(Id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.Proveedor.View.VProveedor_01Lista[]> Proveedor_01ListarXIdAsync(int Id) {
            return base.Channel.Proveedor_01ListarXIdAsync(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESENTER.ServiceDesktop.ProductoGuardarResponse PRESENTER.ServiceDesktop.IServiceDesktop.ProductoGuardar(PRESENTER.ServiceDesktop.ProductoGuardarRequest request) {
            return base.Channel.ProductoGuardar(request);
        }
        
        public bool ProductoGuardar(ENTITY.Producto.View.VProducto proveedor, ref int id) {
            PRESENTER.ServiceDesktop.ProductoGuardarRequest inValue = new PRESENTER.ServiceDesktop.ProductoGuardarRequest();
            inValue.proveedor = proveedor;
            inValue.id = id;
            PRESENTER.ServiceDesktop.ProductoGuardarResponse retVal = ((PRESENTER.ServiceDesktop.IServiceDesktop)(this)).ProductoGuardar(inValue);
            id = retVal.id;
            return retVal.ProductoGuardarResult;
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.ProductoGuardarResponse> ProductoGuardarAsync(PRESENTER.ServiceDesktop.ProductoGuardarRequest request) {
            return base.Channel.ProductoGuardarAsync(request);
        }
        
        public bool ProductoModificar(ENTITY.Producto.View.VProducto proveedor, int id) {
            return base.Channel.ProductoModificar(proveedor, id);
        }
        
        public System.Threading.Tasks.Task<bool> ProductoModificarAsync(ENTITY.Producto.View.VProducto proveedor, int id) {
            return base.Channel.ProductoModificarAsync(proveedor, id);
        }
        
        public bool ProductoEliminar(int id) {
            return base.Channel.ProductoEliminar(id);
        }
        
        public System.Threading.Tasks.Task<bool> ProductoEliminarAsync(int id) {
            return base.Channel.ProductoEliminarAsync(id);
        }
        
        public ENTITY.Producto.View.VProducto[] ProductoListarXId(int id) {
            return base.Channel.ProductoListarXId(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.Producto.View.VProducto[]> ProductoListarXIdAsync(int id) {
            return base.Channel.ProductoListarXIdAsync(id);
        }
        
        public ENTITY.Producto.View.VProductoLista[] ProductoListar() {
            return base.Channel.ProductoListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.Producto.View.VProductoLista[]> ProductoListarAsync() {
            return base.Channel.ProductoListarAsync();
        }
        
        public bool ProductoExisteEnCompra(int id) {
            return base.Channel.ProductoExisteEnCompra(id);
        }
        
        public System.Threading.Tasks.Task<bool> ProductoExisteEnCompraAsync(int id) {
            return base.Channel.ProductoExisteEnCompraAsync(id);
        }
        
        public ENTITY.inv.Sucursal.View.VSucursalCombo[] SucursalListarCombo() {
            return base.Channel.SucursalListarCombo();
        }
        
        public System.Threading.Tasks.Task<ENTITY.inv.Sucursal.View.VSucursalCombo[]> SucursalListarComboAsync() {
            return base.Channel.SucursalListarComboAsync();
        }
        
        public ENTITY.inv.Sucursal.View.VSucursalLista[] SucursalListar() {
            return base.Channel.SucursalListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.inv.Sucursal.View.VSucursalLista[]> SucursalListarAsync() {
            return base.Channel.SucursalListarAsync();
        }
        
        public ENTITY.reg.PrecioCategoria.View.VPrecioCategoria[] PrecioCategoriaListar() {
            return base.Channel.PrecioCategoriaListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.reg.PrecioCategoria.View.VPrecioCategoria[]> PrecioCategoriaListarAsync() {
            return base.Channel.PrecioCategoriaListarAsync();
        }
        
        public ENTITY.reg.Precio.View.VPrecioLista[] PrecioProductoListar(int idSucursal) {
            return base.Channel.PrecioProductoListar(idSucursal);
        }
        
        public System.Threading.Tasks.Task<ENTITY.reg.Precio.View.VPrecioLista[]> PrecioProductoListarAsync(int idSucursal) {
            return base.Channel.PrecioProductoListarAsync(idSucursal);
        }
        
        public ENTITY.com.CompraIngreso.View.VCompraIngreso[] CmmpraIngresoListar() {
            return base.Channel.CmmpraIngresoListar();
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngreso[]> CmmpraIngresoListarAsync() {
            return base.Channel.CmmpraIngresoListarAsync();
        }
        
        public ENTITY.com.CompraIngreso.View.VCompraIngresoLista[] CmmpraIngresoListarXId(int id) {
            return base.Channel.CmmpraIngresoListarXId(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngresoLista[]> CmmpraIngresoListarXIdAsync(int id) {
            return base.Channel.CmmpraIngresoListarXIdAsync(id);
        }
        
        public ENTITY.com.CompraIngreso.View.VCompraIngresoNota[] CompraIngreso_NotaXId(int id) {
            return base.Channel.CompraIngreso_NotaXId(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.CompraIngreso.View.VCompraIngresoNota[]> CompraIngreso_NotaXIdAsync(int id) {
            return base.Channel.CompraIngreso_NotaXIdAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESENTER.ServiceDesktop.CompraIngreso_GuardarResponse PRESENTER.ServiceDesktop.IServiceDesktop.CompraIngreso_Guardar(PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest request) {
            return base.Channel.CompraIngreso_Guardar(request);
        }
        
        public bool CompraIngreso_Guardar(ENTITY.com.CompraIngreso.View.VCompraIngresoLista proveedor, ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] detalle, ref int id, string usuario) {
            PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest inValue = new PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest();
            inValue.proveedor = proveedor;
            inValue.detalle = detalle;
            inValue.id = id;
            inValue.usuario = usuario;
            PRESENTER.ServiceDesktop.CompraIngreso_GuardarResponse retVal = ((PRESENTER.ServiceDesktop.IServiceDesktop)(this)).CompraIngreso_Guardar(inValue);
            id = retVal.id;
            return retVal.CompraIngreso_GuardarResult;
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.CompraIngreso_GuardarResponse> CompraIngreso_GuardarAsync(PRESENTER.ServiceDesktop.CompraIngreso_GuardarRequest request) {
            return base.Channel.CompraIngreso_GuardarAsync(request);
        }
        
        public System.Data.DataTable CompraIngreso_ListarEncabezado() {
            return base.Channel.CompraIngreso_ListarEncabezado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CompraIngreso_ListarEncabezadoAsync() {
            return base.Channel.CompraIngreso_ListarEncabezadoAsync();
        }
        
        public ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] CmmpraIngreso_01ListarXId(int id) {
            return base.Channel.CmmpraIngreso_01ListarXId(id);
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.CompraIngreso_01.VCompraIngreso_01[]> CmmpraIngreso_01ListarXIdAsync(int id) {
            return base.Channel.CmmpraIngreso_01ListarXIdAsync(id);
        }
        
        public ENTITY.com.CompraIngreso_01.VCompraIngreso_01[] CmmpraIngreso_01ListarXId2(int IdGrupo2) {
            return base.Channel.CmmpraIngreso_01ListarXId2(IdGrupo2);
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.CompraIngreso_01.VCompraIngreso_01[]> CmmpraIngreso_01ListarXId2Async(int IdGrupo2) {
            return base.Channel.CmmpraIngreso_01ListarXId2Async(IdGrupo2);
        }
        
        public ENTITY.com.Seleccion.View.VSeleccionLista[] Seleccion_Lista() {
            return base.Channel.Seleccion_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.Seleccion.View.VSeleccionLista[]> Seleccion_ListaAsync() {
            return base.Channel.Seleccion_ListaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESENTER.ServiceDesktop.Seleccion_GuardarResponse PRESENTER.ServiceDesktop.IServiceDesktop.Seleccion_Guardar(PRESENTER.ServiceDesktop.Seleccion_GuardarRequest request) {
            return base.Channel.Seleccion_Guardar(request);
        }
        
        public bool Seleccion_Guardar(ENTITY.com.Seleccion.View.VSeleccion vSeleccion, ENTITY.com.Seleccion_01.View.VSeleccion_01[] detalle, ref int id, string usuario) {
            PRESENTER.ServiceDesktop.Seleccion_GuardarRequest inValue = new PRESENTER.ServiceDesktop.Seleccion_GuardarRequest();
            inValue.vSeleccion = vSeleccion;
            inValue.detalle = detalle;
            inValue.id = id;
            inValue.usuario = usuario;
            PRESENTER.ServiceDesktop.Seleccion_GuardarResponse retVal = ((PRESENTER.ServiceDesktop.IServiceDesktop)(this)).Seleccion_Guardar(inValue);
            id = retVal.id;
            return retVal.Seleccion_GuardarResult;
        }
        
        public System.Threading.Tasks.Task<PRESENTER.ServiceDesktop.Seleccion_GuardarResponse> Seleccion_GuardarAsync(PRESENTER.ServiceDesktop.Seleccion_GuardarRequest request) {
            return base.Channel.Seleccion_GuardarAsync(request);
        }
        
        public ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[] Seleccion_01_Lista() {
            return base.Channel.Seleccion_01_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[]> Seleccion_01_ListaAsync() {
            return base.Channel.Seleccion_01_ListaAsync();
        }
        
        public ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[] Seleccion_01_ListarXId_Vacio(int IdCompraInreso_01) {
            return base.Channel.Seleccion_01_ListarXId_Vacio(IdCompraInreso_01);
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.Seleccion_01.View.VSeleccion_01_Lista[]> Seleccion_01_ListarXId_VacioAsync(int IdCompraInreso_01) {
            return base.Channel.Seleccion_01_ListarXId_VacioAsync(IdCompraInreso_01);
        }
        
        public ENTITY.inv.Transformacion.View.VTransformacion[] Transformacion_Lista() {
            return base.Channel.Transformacion_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.inv.Transformacion.View.VTransformacion[]> Transformacion_ListaAsync() {
            return base.Channel.Transformacion_ListaAsync();
        }
        
        public ENTITY.inv.Transformacion_01.View.VTransformacion_01_Lista[] Transformacion_01_Lista() {
            return base.Channel.Transformacion_01_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.inv.Transformacion_01.View.VTransformacion_01_Lista[]> Transformacion_01_ListaAsync() {
            return base.Channel.Transformacion_01_ListaAsync();
        }
        
        public ENTITY.com.Compra.View.VCompraLista[] Compra_Lista() {
            return base.Channel.Compra_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.Compra.View.VCompraLista[]> Compra_ListaAsync() {
            return base.Channel.Compra_ListaAsync();
        }
        
        public ENTITY.com.Compra_01.View.VCompra_01_Lista[] Compra_01_Lista() {
            return base.Channel.Compra_01_Lista();
        }
        
        public System.Threading.Tasks.Task<ENTITY.com.Compra_01.View.VCompra_01_Lista[]> Compra_01_ListaAsync() {
            return base.Channel.Compra_01_ListaAsync();
        }
    }
}
